# The URL the site will be built for
base_url = "https://piannaf.com"

# The site theme to use
theme = "kodama-theme"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

title = "Justin Mancinelli"

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = false

[translations]
Biography = "Biography"
Interests = "Interests"
Education = "Education"
toc = "Table of Contents"
Published = "Published"
Abstract = "Abstract"
volume = "volume"
number = "number"
pages = "pages"

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = false

[extra]
# Image of your avatar displayed on the landing page
avatar = "static/images/portrait.jpg"
# Image of the favicon
favicon = "static/images/portrait.jpg"

# Your email address showed in the contact section
email = "justin.mancinelli@gmail.com"

# If you don't want to show your contact information in the index
contact_in_index = true

# Additional menu items
# `Name` is what it is displayed, `path` is the url
menu_items = [
  # { path = "#contacts", name = "Contact" },
]